[[override]]
  name = "k8s.io/code-generator"
  # revision for tag "kubernetes-1.13.1"
  revision = "c2090bec4d9b1fb25de3812f868accc2bc9ecbae"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "0cf8f7e6ed1d2e3d47d02e3b6e559369af24d803"

[[override]]
  name = "github.com/go-openapi/spec"
  branch = "master"

[[override]]
  name = "k8s.io/api"
  # revision for tag "kubernetes-1.14.1"
  revision = "6e4e0e4f393bf5e8bbff570acd13217aa5a770cd"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  # revision for tag "kubernetes-1.14.1"
  revision = "727a075fdec8319bf095330e344b3ccc668abc73"

[[override]]
  name = "k8s.io/apimachinery"
  # revision for tag "kubernetes-1.14.1"
  revision = "6a84e37a896db9780c75367af8d2ed2bb944022e"

[[override]]
  name = "k8s.io/client-go"
  # revision for tag "kubernetes-1.14.1"
  revision = "1a26190bd76a9017e289958b9fba936430aa3704"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "=v0.31.1"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.2.2"

[[override]]
  name = "github.com/intel/sriov-network-device-plugin"
  branch = "master"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "=v0.11.0"

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false

  [[prune.project]]
    name = "k8s.io/gengo"
    non-go = false
