---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-cni
  namespace: sriov-network-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-device-plugin
  namespace: sriov-network-operator
