apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriov-network-operator
roleRef:
  kind: ClusterRole
  name: sriov-network-operator
subjects:
- kind: ServiceAccount
  namespace: $NAMESPACE
  name: sriov-network-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriov-network-config-daemon
roleRef:
  kind: ClusterRole
  name: sriov-network-config-daemon
subjects:
- kind: ServiceAccount
  namespace: $NAMESPACE
  name: sriov-network-config-daemon

