apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriov-network-operator
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: [namespaces, serviceaccounts, ]
  verbs: ["*"]
- apiGroups: [rbac.authorization.k8s.io]
  resources: [rolebindings, roles]
  verbs: ["*"]
