apiVersion: apps/v1
kind: Deployment
metadata:
  name: sriov-network-operator
  namespace: sriov-network-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sriov-network-operator
  template:
    metadata:
      labels:
        name: sriov-network-operator
    spec:
      serviceAccountName: sriov-network-operator
      containers:
        - name: sriov-network-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - sriov-network-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sriov-network-operator"
